/**
 * SQL Engine Laboratory — Oracle Free Engine Adapter
 *
 * Definición del motor Oracle Free para el catálogo de motores.
 * Basado en gvenzl/oracle-free 23.5 (soporte arm64 nativo).
 * Puerto por defecto: 1521
 * Cliente nativo: sqlplus
 *
 * Oracle usa PDBs (Pluggable Databases) en vez del modelo clásico de BD.
 * El laboratorio usa FREEPDB1 como PDB por defecto.
 *
 * Atribución: configuración basada en el trabajo de Gerald Venzl (gvenzl/oracle-free).
 */

import { EngineDefinition } from './engine.types';

export const oracleEngine: EngineDefinition = {
  id: 'oracle',
  displayName: 'Oracle Free',
  description: 'Oracle Database Free 23ai — motor enterprise con licencia gratuita para desarrollo',
  defaultPort: 1521,
  dockerEnvValue: 'oracle',
  connectionTemplate: {
    command: 'sqlplus',
    argsTemplate: '{user}/{password}@{host}:{port}/FREEPDB1',
    defaultUser: 'labuser',
    defaultPassword: 'labpassword',
    defaultDatabase: 'FREEPDB1',
    adminUser: 'sys as sysdba',
    adminPassword: 'labpassword',
    adminPasswordMessage: 'Misma que el usuario del laboratorio',
    testCommands: [
      "SELECT * FROM v$version;",
      "CREATE TABLE test (id NUMBER GENERATED BY DEFAULT AS IDENTITY, nombre VARCHAR2(50));",
      "INSERT INTO test (nombre) VALUES ('Hola Lab');",
      "SELECT * FROM test;"
    ],
  },
  healthcheckTimeoutMs: 120000,
  startupSpeed: 'slow',
  iconId: 'database',
};
