/**
 * SQL Engine Laboratory — Enriched Tutorial Database
 *
 * Contiene consejos, ideas, casos de uso, casos reales y noticias
 * para cada módulo de aprendizaje de los 6 motores soportados.
 */

export interface EnrichedChapter {
  consejos: string[];
  ideas: string[];
  casosDeUso: string[];
  casosReales: string[];
  noticias: string[];
  
  // UDL & Gamification Fields (Hachimaki DB Sensei Academy)
  lore_context?: string;
  technical_deep_dive?: string;
  visual_analogy?: string;
  interactive_challenge?: string;
}

const postgresChapters: Record<string, EnrichedChapter> = {
  "1-1": {
    consejos: [
      "Evita usar SERIAL en nuevas tablas si estás en PostgreSQL 10 o superior; prefiere GENERATED BY DEFAULT AS IDENTITY que es estándar SQL.",
      "El tipo TEXT en PostgreSQL no tiene penalizaciones de rendimiento en comparación con VARCHAR(N). Úsalo con confianza si no requieres limitar la longitud."
    ],
    ideas: [
      "Añade una restricción CHECK en la columna de habilidades para evitar que se guarden arrays vacíos.",
      "Prueba a insertar habilidades adicionales usando la sintaxis ARRAY['Habilidad1', 'Habilidad2'] y realiza un SELECT."
    ],
    casosDeUso: [
      "Uso de arrays para tags/etiquetas de artículos en sistemas de blogs sin requerir una tabla intermedia (mientras el volumen sea moderado).",
      "UUIDs para claves primarias en sistemas distribuidos que evitan colisiones de ID al sincronizar datos."
    ],
    casosReales: [
      "Una startup fintech paralizó sus operaciones por 4 horas debido a que su clave primaria de transacciones usaba SERIAL (entero de 32 bits) y desbordó su valor máximo (2,147,483,647). Tuvieron que migrar en caliente a BIGINT.",
      "El uso indiscriminado de UUID v4 (aleatorios) como clave primaria en tablas de gran escala provocó fragmentación extrema en el índice B-Tree, ralentizando las inserciones en un 70% debido a constantes reordenamientos en disco."
    ],
    noticias: [
      "PostgreSQL 17 introdujo mejoras significativas en el rendimiento de consultas sobre tipos de datos complejos y arrays.",
      "El estándar SQL:2023 ha incluido soporte formal para múltiples operaciones que PostgreSQL ya soportaba de manera nativa."
    ],
    lore_context: "[SEÑAL ENCRIPTADA] Operativo, ingresamos al servidor central de la corporación fantasma. Debes construir la estructura base para indexar a sus contratistas de alto riesgo sin llamar la atención de sus sistemas IDS locales.",
    technical_deep_dive: "Evita SERIAL en producción a gran escala: no cumple con el estándar SQL y genera bloqueos implícitos de secuencia. GENERATED BY DEFAULT AS IDENTITY utiliza secuencias estándar ANSI ligadas al ciclo de vida de la columna. El uso de arrays nativos (TEXT[]) optimiza lecturas sin joins, pero viola la 1NF. Úsalo con cautela.",
    visual_analogy: "Imagina un archivero donde cada cajón tiene un autoincrementador mecánico (SERIAL). Si dos secretarias intentan sacar un número al mismo tiempo, el autoincrementador puede trabarse. La IDENTITY es un despachador electrónico integrado directamente en la cerradura del cajón.",
    interactive_challenge: ">> DESAFÍO: Inserta un piloto rebelde agregando una columna 'fecha_registro' con default CURRENT_TIMESTAMP. Tu recompensa son 100 XP en DDL."
  },
  "1-2": {
    consejos: [
      "Asigna nombres explícitos a tus restricciones (constraints). Un error como 'violates check constraint chk_pilotos_creditos' es mucho mejor que 'violates check constraint pilotos_check'.",
      "Agregar una restricción CHECK a una tabla grande bloquea la tabla para validar filas. Considera crearla como NOT VALID y luego validarla con VALIDATE CONSTRAINT."
    ],
    ideas: [
      "Escribe un INSERT que intente violar la restricción de créditos negativos y observa la estructura del error arrojado por el motor.",
      "Crea una restricción que asegure que el nombre del piloto contenga al menos 3 caracteres."
    ],
    casosDeUso: [
      "Restricciones CHECK para asegurar que estados de pedidos sigan un conjunto cerrado de valores ('pendiente', 'pagado', 'enviado').",
      "Claves únicas compuestas (UNIQUE) para evitar que un usuario registre dos veces la misma dirección de correo."
    ],
    casosReales: [
      "Un bug en la capa de negocio de un exchange permitió saldos negativos debido a que la validación solo existía en el frontend. Si se hubiera definido un CHECK constraint en la base de datos, el motor habría abortado las transacciones y evitado pérdidas millonarias."
    ],
    noticias: [
      "La comunidad de PostgreSQL discute la inclusión de restricciones lógicas más dinámicas que involucren consultas externas en futuras versiones."
    ],
    lore_context: "La base de datos del reactor de fusión carece de límites de presión. Si no aplicas restricciones CHECK directamente en las columnas, un overflow físico simulará un colapso total (muhahahahah).",
    technical_deep_dive: "Las restricciones CHECK operan a nivel de fila durante la fase de validación de tupla. Al ejecutar ALTER TABLE ADD CONSTRAINT, PostgreSQL bloquea la tabla en modo Access Exclusive, impidiendo cualquier lectura/escritura concurrentes mientras valida los datos existentes. En bases grandes de nivel bancario, usa NOT VALID y luego ejecuta VALIDATE CONSTRAINT para evitar timeouts catastróficos.",
    visual_analogy: "Un constraint CHECK es como un filtro en la entrada de aire del reactor. Si dejas que el aire pase y confías en la computadora externa para filtrarlo, tarde o temprano entrará polvo. Poner el constraint en el motor es soldar el filtro directamente en la tubería de acero.",
    interactive_challenge: ">> DESAFÍO: Añade una regla UNIQUE combinada para evitar pilotos duplicados en el mismo sector galáctico. Logra la compilación limpia del DDL para obtener 150 XP."
  },
  "1-3": {
    consejos: [
      "Usa la cláusula RETURNING en tus sentencias INSERT o UPDATE para recuperar valores generados automáticamente sin realizar un SELECT extra.",
      "Nunca concatenes variables directamente en tus sentencias DML. Usa consultas parametrizadas para evitar inyección SQL."
    ],
    ideas: [
      "Usa el operador ANY en un SELECT para filtrar pilotos que tengan la habilidad 'Fuerza' dentro de su array.",
      "Prueba un comando UPDATE para duplicar los créditos de todos los pilotos rebeldes de una sola vez."
    ],
    casosDeUso: [
      "Uso de RETURNING para obtener el ID de un registro recién creado para insertarlo inmediatamente en una tabla de auditoría en la misma transacción."
    ],
    casosReales: [
      "Un desarrollador junior ejecutó un UPDATE sin WHERE en una tabla de clientes en producción pensando que la terminal estaba en modo seguro. Afectó a 3 millones de registros. Afortunadamente, se restauró una copia de seguridad point-in-time (PITR)."
    ],
    noticias: [
      "PostgreSQL ha optimizado el rendimiento de la cláusula DML MERGE introducida en la versión 15, haciéndola competitiva frente a INSERT ON CONFLICT."
    ],
    lore_context: "Necesitamos extraer los créditos de las cuentas durmientes para financiar la resistencia clandestina. Pero ten cuidado: el backend de la corporación registra cada transacción inusual.",
    technical_deep_dive: "La cláusula RETURNING en DML evita hacer un roundtrip innecesario de red (SELECT adicional) al retornar los valores calculados directamente en el pipe de respuesta. La inyección SQL ocurre cuando concatenas strings directamente en el parse del motor, permitiendo al atacante inyectar un terminador de consulta (';') y sentencias destructivas.",
    visual_analogy: "Un UPDATE sin WHERE es como tirar una bomba de racimo en un centro comercial para atrapar a un solo sospechoso. RETURNING es como pedirle al sospechoso que se identifique inmediatamente después de atraparlo, en lugar de buscar en todo el edificio de nuevo.",
    interactive_challenge: ">> DESAFÍO: Realiza un SELECT filtrando pilotos rebeldes usando el operador ANY sobre la columna de arrays. Hazlo en menos de 10 milisegundos para ganar 200 XP."
  },
  "2-1": {
    consejos: [
      "Al hacer JOIN, asegúrate de tener índices en las llaves foráneas. Postgres no crea índices automáticos para foreign keys, a diferencia de otros motores.",
      "Prefiere INNER JOIN sobre LEFT JOIN cuando sabes que la relación siempre existe; esto ayuda al planificador a elegir mejores rutas."
    ],
    ideas: [
      "Escribe un FULL OUTER JOIN para encontrar tanto naves sin piloto como pilotos sin nave.",
      "Añade un piloto con nave asignada y luego intenta borrar al piloto. Observa cómo el constraint FOREIGN KEY bloquea la operación."
    ],
    casosDeUso: [
      "Relacionar tablas de usuarios y perfiles manteniendo integridad referencial dura.",
      "Construir reportes de ventas cruzando facturas con clientes mediante JOINs rápidos."
    ],
    casosReales: [
      "Una empresa SaaS experimentó lentitud extrema en sus reportes mensuales. El diagnóstico reveló que las tablas tenían llaves foráneas pero carecían de índices en las columnas `_id` de origen, obligando a Postgres a realizar escaneos secuenciales completos (Sequential Scans)."
    ],
    noticias: [
      "El optimizador de consultas de Postgres en sus versiones recientes utiliza paralelismo avanzado para acelerar Hash Joins en tablas de varios gigabytes."
    ],
    lore_context: "Hemos interceptado los manifiestos de las naves imperiales. Hay naves fantasma volando sin piloto asignado. Debemos cruzar los datos para exponer a los contrabandistas.",
    technical_deep_dive: "A diferencia de Oracle y SQL Server, PostgreSQL no crea automáticamente índices en las llaves foráneas. Al borrar un registro de la tabla padre, el motor realiza un Sequential Scan completo en la tabla hija para validar la integridad referencial, bloqueando filas y degradando el rendimiento en sistemas bancarios. Crea índices manuales en todas tus FKs.",
    visual_analogy: "Hacer un JOIN sin índices en la llave foránea es como buscar a un criminal en una ciudad pidiendo la identificación puerta por puerta en cada colonia (Sequential Scan) en lugar de usar un archivo de sospechosos clasificados por nombre.",
    interactive_challenge: ">> DESAFÍO: Ejecuta un LEFT JOIN y un FULL JOIN combinados para encontrar naves sin piloto y pilotos sin naves asignadas. Expon los registros huérfanos y reclama 250 XP."
  },
  "2-2": {
    consejos: [
      "Utiliza el tipo de datos JSONB en lugar de JSON. JSONB se guarda en un formato binario descompuesto, lo que permite crear índices y búsquedas ultra rápidas.",
      "No abuses de JSONB para datos estructurados que encajan perfectamente en columnas tradicionales. Pierdes tipado rígido y protección de constraints."
    ],
    ideas: [
      "Usa el operador de contención `@>` para buscar naves que tengan en sus especificaciones la propiedad `\"hiperimpulsor\": true`.",
      "Escribe un query para actualizar el JSONB agregando una nueva propiedad `\"tripulacion\": 4`."
    ],
    casosDeUso: [
      "Almacenar metadatos dinámicos de productos cuyos atributos varían drásticamente (ej: ropa vs electrónica).",
      "Logs de integración con APIs de terceros donde la estructura del payload puede cambiar sin previo aviso."
    ],
    casosReales: [
      "Un e-commerce migró su catálogo dinámico a tablas relacionales rígidas con 200 columnas con valor nulo. El rendimiento se desplomó. Volvieron a un diseño híbrido usando JSONB indexado con índices GIN, reduciendo el tamaño de almacenamiento en un 40% y mejorando la velocidad."
    ],
    noticias: [
      "El soporte para JSON Schema y validaciones directas dentro de campos JSONB es uno de los temas más activos en las conferencias anuales de Postgres."
    ],
    lore_context: "Los planos de las estaciones militares se guardan en metadatos desestructurados JSON. Tu misión es extraer las especificaciones de blindaje térmico del reactor sin deserializar todo el documento en memoria.",
    technical_deep_dive: "JSONB descompone el JSON de entrada en un formato binario estructurado y ordenado. Esto permite indexación directa mediante índices GIN (Generalized Inverted Index) y búsquedas ultra veloces con operadores de contención como `@>`. El tipo JSON clásico, en cambio, guarda el texto exacto, obligando a parsearlo en cada ejecución.",
    visual_analogy: "JSON normal es como un libro físico sellado que debes abrir y leer de inicio a fin para encontrar una palabra. JSONB es como tener el libro ya resumido en un índice temático digital en tu pantalla.",
    interactive_challenge: ">> DESAFÍO: Extrae la velocidad máxima de la nave usando el operador de extracción rápida (->>) de JSONB. Recupera el valor y desbloquea 300 XP."
  },
  "2-3": {
    consejos: [
      "Las vistas materializadas (Materialized Views) guardan físicamente el resultado de la consulta. Úsalas para reportes pesados, pero recuerda ejecutar REFRESH MATERIALIZED VIEW.",
      "Las CTE (WITH) en Postgres 12+ ya no actúan como barreras de optimización por defecto. El optimizador puede mezclar la consulta interna en la principal para mayor velocidad."
    ],
    ideas: [
      "Crea una vista materializada de pilotos ricos y actualízala manualmente después de modificar los créditos de un piloto.",
      "Escribe una consulta recursiva usando WITH RECURSIVE para generar una secuencia numérica o una estructura jerárquica sencilla."
    ],
    casosDeUso: [
      "Simplificar consultas complejas exponiendo vistas limpias al equipo de analistas de datos.",
      "Almacenar agregaciones de reportes financieros diarios que solo cambian una vez al día mediante vistas materializadas."
    ],
    casosReales: [
      "Un panel de administración cargaba datos históricos tardando 12 segundos por petición. El equipo implementó una vista materializada que se refrescaba cada hora en segundo plano, bajando el tiempo de respuesta a 8 milisegundos."
    ],
    noticias: [
      "Postgres 16 habilitó el refresco de vistas materializadas en paralelo bajo ciertas condiciones, disminuyendo a la mitad el tiempo de bloqueo."
    ],
    lore_context: "El cuartel general requiere un reporte en tiempo real de los pilotos más acaudalados. Pero la consulta base tarda segundos y ralentiza el panel de control táctico.",
    technical_deep_dive: "Las vistas materializadas almacenan físicamente en disco el resultado de la consulta. Requieren refresco manual (REFRESH MATERIALIZED VIEW), el cual por defecto adquiere un bloqueo exclusivo sobre la vista. A partir de PostgreSQL 12, las CTE (WITH) no se materializan automáticamente por defecto (not materialized), permitiendo que el planificador combine y optimice la consulta externa con la interna.",
    visual_analogy: "Una vista normal es una ventana mágica que calcula la escena cada vez que miras. Una vista materializada es una fotografía instantánea guardada en el escritorio. Es instantánea de mirar, pero debes tomar una foto nueva si la realidad cambia.",
    interactive_challenge: ">> DESAFÍO: Crea una vista materializada de los rebeldes con créditos superiores a 50,000. Refresca la vista y cobra tus 350 XP."
  },
  "3-1": {
    consejos: [
      "Agente, el nivel de aislamiento SERIALIZABLE protege contra transacciones fantasma (Phantom Reads), pero disminuye el rendimiento drásticamente. Úsalo solo en ledgers financieros intocables.",
      "Evita triggers complejos en Postgres cuando manejas alta concurrencia; el overhead de contexto PL/pgSQL puede llevar al colapso del sistema en un Black Friday."
    ],
    ideas: [
      "Abre dos pestañas de terminal conectadas al contenedor, inicia dos transacciones simultáneas e intenta forzar un 'Deadlock' cruzando updates.",
      "Investiga la vista pg_stat_activity para encontrar quién está bloqueando tu query cuando el sistema no responde."
    ],
    casosDeUso: [
      "Sistemas bancarios core donde un céntimo perdido o duplicado significa una auditoría federal inmediata.",
      "Plataformas de trading de alta frecuencia (HFT) donde el orden exacto de las operaciones es crítico."
    ],
    casosReales: [
      "En 2018, un exchange cripto asiático perdió $3 millones porque su base no estaba configurada en modo SERIALIZABLE, permitiendo retiros concurrentes del mismo saldo debido a una condición de carrera ('Double Spend')."
    ],
    noticias: [
      "Las optimizaciones de MVCC en las últimas versiones (basadas en snapshots) mejoran dramáticamente la velocidad de limpieza de filas muertas (autovacuum)."
    ],
    lore_context: "[SEÑAL DE ALTA PRIORIDAD] Operativo Hachimaki, un sindicato rival está intentando realizar ataques de 'Doble Gasto' en las bóvedas corporativas. Tu misión es asegurar el ledger aplicando aislamiento absoluto. Si fallas, vaciarán nuestras reservas en milisegundos. (muhahahahah).",
    technical_deep_dive: "MVCC permite que los 'lectores no bloqueen a los escritores y los escritores no bloqueen a los lectores'. Cada fila tiene una versión oculta (xmin, xmax). SERIALIZABLE en Postgres usa bloqueos SSI (Serializable Snapshot Isolation) que detectan dependencias de lectura/escritura anómalas y abortan proactivamente la transacción infractora con un 'serialization failure'.",
    visual_analogy: "Imagina un sistema de control de trenes donde cada tren (transacción) tiene su propia foto instantánea de las vías (Snapshot). Si dos trenes intentan reclamar la misma vía basándose en fotos viejas y conflictivas, el sistema descarrilará uno a propósito (Rollback) para salvar el tren principal.",
    interactive_challenge: ">> MISIÓN ACTIVA: Configura el nivel de aislamiento a SERIALIZABLE e intenta provocar un error 'serialization failure' cruzando updates en dos terminales separadas. Repórtate a la base cuando lo logres para cobrar tu recompensa."
  },
  "3-2": {
    consejos: [
      "Usa funciones estándar para calcular valores simples y Stored Procedures (procedimientos almacenados) si necesitas control de transacciones (COMMIT y ROLLBACK adentro).",
      "Define tus funciones como STABLE o IMMUTABLE si no modifican datos; esto permite a Postgres cachear los resultados y optimizar el plan."
    ],
    ideas: [
      "Escribe una función que retorne el promedio de créditos de los pilotos de un bando específico.",
      "Crea un procedimiento que realice una transferencia de créditos entre dos pilotos, validando que el saldo de origen sea suficiente antes de proceder."
    ],
    casosDeUso: [
      "Centralizar lógica de negocio crítica en la base de datos para que múltiples aplicaciones (Node, Go, Python) la consuman con las mismas reglas.",
      "Procesos batch nocturnos de depuración de registros obsoletos usando transacciones controladas."
    ],
    casosReales: [
      "Un banco regional centralizó el cálculo de tasas de interés complejas en una función PL/pgSQL IMMUTABLE. Cuando actualizaron su API backend de Ruby a Go, no tuvieron que reescribir ni una sola línea de lógica financiera."
    ],
    noticias: [
      "La integración de motores de ejecución alternativos (como WebAssembly) dentro de Postgres para escribir funciones en Rust o C++ sigue ganando tracción en el ecosistema open source."
    ],
    lore_context: "Hemos detectado un intento de hackeo de saldos. La lógica de cálculo de dividendos debe mudarse de la aplicación (Node/Python) directamente al núcleo de la base de datos para evitar alteraciones en tránsito.",
    technical_deep_dive: "Las funciones de PL/pgSQL se ejecutan dentro del proceso del backend. Declararlas como STABLE o IMMUTABLE le dice al optimizador que el resultado es determinista ante las mismas entradas, permitiendo cachear planes y saltarse ejecuciones repetitivas. Los Stored Procedures (introducidos en PG 11+) permiten control transaccional nativo (COMMIT/ROLLBACK internos), a diferencia de las funciones.",
    visual_analogy: "Calcular los dividendos en Node.js es como enviar camiones llenos de oro (datos) por una carretera peligrosa de red hasta la oficina de cálculo, para luego devolverlos. Hacerlo en un Stored Procedure es fundir y procesar el oro directamente en la bóveda sin sacarlo al exterior.",
    interactive_challenge: ">> DESAFÍO: Escribe una función PL/pgSQL declarada como STABLE que calcule el saldo promedio de un bando galáctico específico. Despliega la función y reclama 450 XP."
  },
  "3-3": {
    consejos: [
      "Usa `pgcrypto` para cifrar datos a nivel de columna si no usas cifrado completo de disco (TDE).",
      "Revisa la lista de extensiones instaladas usando `SELECT * FROM pg_available_extensions;` para conocer el potencial de tu instalación."
    ],
    ideas: [
      "Instala la extensión `fuzzystrmatch` y usa la función `levenshtein` para buscar nombres de pilotos similares a pesar de errores tipográficos.",
      "Prueba a cifrar y descifrar un texto simple usando las funciones de pgcrypto."
    ],
    casosDeUso: [
      "Encriptar datos altamente sensibles como números de identificación médica o tokens de acceso a APIs externas.",
      "Búsquedas geográficas utilizando la extensión PostGIS para geolocalizar conductores u oficinas."
    ],
    casosReales: [
      "Una aplicación de delivery líder en Latinoamérica utiliza PostGIS para calcular las rutas óptimas y asignar repartidores en tiempo real, procesando millones de consultas espaciales por segundo sobre PostgreSQL."
    ],
    noticias: [
      "La extensión `pgvector` ha revolucionado el ecosistema, convirtiendo a Postgres en la base de datos de vectores preferida para almacenar embeddings de Inteligencia Artificial."
    ],
    lore_context: "Los espías imperiales viajan usando identidades encriptadas. Debes utilizar criptografía simétrica a nivel de columna para asegurar sus bitácoras de vuelo y geolocalizar sus naves nodrizas.",
    technical_deep_dive: "PostgreSQL destaca por su extensibilidad. pgcrypto expone hashing robusto (SCRAM-SHA-256, Blowfish) y funciones de encriptación simétrica/asimétrica. PostGIS añade tipos geométricos y espaciales indexados con R-Trees, permitiendo resolver consultas espaciales en milisegundos mediante índices GiST.",
    visual_analogy: "Una base de datos ordinaria es como una calculadora científica básica. Instalar pgcrypto y PostGIS es como añadirle un módulo de GPS militar y una máquina Enigma integrada de cifrado físico.",
    interactive_challenge: ">> DESAFÍO: Cifra un token de seguridad sensible usando la función crypt de pgcrypto con sal Blowfish (bf). Realiza la encriptación y alcanza el nivel Máster con 500 XP."
  }
};

const sqliteChapters: Record<string, EnrichedChapter> = {
  "1-1": {
    consejos: [
      "SQLite usa Tipado Dinámico (Manifest Typing). El tipo que declaras en la tabla es solo una recomendación (afinidad). Puedes guardar texto en un campo INTEGER.",
      "Usa la columna especial `rowid` para búsquedas súper rápidas si no defines una clave primaria entera explícita."
    ],
    ideas: [
      "Inserta un registro con una cadena de texto en la columna de capacidad y verifica con la función `typeof()` qué tipo se almacenó.",
      "Crea una tabla sin clave primaria y haz un SELECT incluyendo la columna oculta `rowid`."
    ],
    casosDeUso: [
      "Almacenamiento local en aplicaciones móviles (iOS/Android) donde los recursos de memoria son limitados.",
      "Formatos de archivo integrados en programas de escritorio (como bases de datos de Adobe Lightroom)."
    ],
    casosReales: [
      "El navegador web Chrome utiliza cientos de bases de datos SQLite locales para guardar tu historial, cookies, contraseñas autocompletadas y caché de búsquedas de forma rápida y persistente."
    ],
    noticias: [
      "SQLite 3.45 introdujo mejoras sustanciales en el análisis sintáctico y optimizaciones para su motor de tipos dinámicos."
    ],
    lore_context: "Operativo, estamos en un sensor de satélite que funciona a batería. No hay RAM para levantar un servidor Postgres de 1 GB. Debes estructurar la base local de SQLite, pero ten cuidado con su tipado dinámico o guardarás basura sin darte cuenta.",
    technical_deep_dive: "SQLite usa tipado dinámico (Manifest Typing). A diferencia de los motores tradicionales, el tipo de datos está asociado al valor en sí, no a la columna. Las columnas tienen 'afinidad' (INTEGER, TEXT, BLOB, REAL, NUMERIC). Si declaras INTEGER y pasas un string que parece número ('123'), lo convertirá; si pasas 'hola', lo guardará como texto. Usa rowid para búsquedas directas.",
    visual_analogy: "Un archivador clásico (Postgres) tiene cajones rígidos donde solo entran carpetas de cierto tamaño. SQLite es una caja de cartón donde puedes meter lo que sea, pero tiene etiquetas recomendadas. Si metes un martillo en el cajón de hojas, el motor no se quejará.",
    interactive_challenge: ">> DESAFÍO: Inserta un string en la columna INTEGER de capacidad y consulta usando la función typeof(). Demuestra la afinidad de tipos y gana 100 XP."
  },
  "1-2": {
    consejos: [
      "ALTER TABLE en SQLite es muy limitado. No puedes eliminar o modificar columnas fácilmente en versiones antiguas sin recrear la tabla.",
      "Para hacer cambios estructurales mayores en SQLite, la práctica recomendada es: crear tabla nueva, copiar datos con INSERT INTO ... SELECT, borrar tabla vieja, renombrar la nueva."
    ],
    ideas: [
      "Intenta renombrar una columna agregada usando ALTER TABLE y verifica si tu versión de SQLite lo soporta directamente.",
      "Modifica la tabla para desactivar temporalmente las claves foráneas usando un PRAGMA antes de alterar estructuras."
    ],
    casosDeUso: [
      "Migraciones estructuradas en sistemas embebidos de bajo consumo."
    ],
    casosReales: [
      "Un desarrollador móvil intentó alterar una columna de una tabla de 10GB en SQLite directamente desde su app. La operación bloqueó el hilo principal (main thread), provocando que el sistema operativo cerrara la aplicación por no responder."
    ],
    noticias: [
      "Las versiones recientes de SQLite han expandido el soporte para ALTER TABLE RENAME COLUMN, reduciendo la necesidad del truco de recreación de tablas."
    ],
    lore_context: "Nuestros agentes cambiaron de bando y la tabla de bases rebeldes necesita reestructurarse con urgencia en el dispositivo embebido. Pero el compilador de SQLite es primitivo...",
    technical_deep_dive: "ALTER TABLE en SQLite históricamente no soportaba DROP COLUMN o ALTER COLUMN de manera directa. El estándar seguro de migración consiste en: 1) Iniciar transacción. 2) Crear tabla temporal con el nuevo esquema. 3) Copiar datos. 4) Eliminar tabla original. 5) Renombrar tabla temporal. 6) Confirmar transacción.",
    visual_analogy: "Modificar una tabla en Postgres es como remodelar un cuarto de tu casa en vivo. En SQLite, es más seguro construir una casa réplica idéntica al lado con la nueva habitación, pasar todas tus cosas y luego demoler la casa vieja.",
    interactive_challenge: ">> DESAFÍO: Renombra la tabla 'bases' a 'bases_rebeldes' usando ALTER TABLE RENAME TO sin corromper el firmware simulado. Obtén 150 XP."
  },
  "1-3": {
    consejos: [
      "SQLite realiza un commit automático para cada inserción DML si no envuelves tus comandos en una transacción (BEGIN TRANSACTION ... COMMIT). Inserciones masivas sin transacción son extremadamente lentas.",
      "Usa la cláusula `INSERT OR IGNORE` o `INSERT OR REPLACE` para resolver conflictos de clave de manera rápida."
    ],
    ideas: [
      "Prueba a insertar 1000 registros usando un bucle con transacciones individuales y luego haz lo mismo envuelto en un único bloque de transacción. Mide la diferencia de velocidad.",
      "Escribe una consulta que limite filas usando la combinación de LIMIT y OFFSET."
    ],
    casosDeUso: [
      "Carga inicial de datos de configuración en videojuegos locales al iniciar sesión.",
      "Cacheo local de datos de red en apps para soportar modo sin conexión (Offline-first)."
    ],
    casosReales: [
      "Una aplicación de escritorio tardaba 2 minutos en importar un archivo CSV de 50,000 líneas. Al agregar un `BEGIN;` al inicio y un `COMMIT;` al final, el tiempo de importación bajó a 0.4 segundos."
    ],
    noticias: [
      "El modo de transacciones de SQLite se ha refinado en las últimas versiones para aumentar la resiliencia ante pérdidas de energía en dispositivos móviles."
    ],
    lore_context: "Estamos cargando 50,000 llaves de acceso en la memoria local. Si lo haces registro por registro sin un bloque de transacción, la CPU del microcontrolador se fundirá antes de terminar.",
    technical_deep_dive: "Por defecto, SQLite opera en modo autocommit implícito. Cada inserción abre y cierra un journal en disco, realizando llamadas pesadas del sistema (fsync). Agrupar inserciones en un bloque transaccional (BEGIN TRANSACTION ... COMMIT) reduce las escrituras físicas a una sola operación de sincronización en disco, multiplicando la velocidad de inserción hasta por 100 veces.",
    visual_analogy: "Hacer 1000 inserciones sin transacción es como ir al supermercado y pagar cada manzana individualmente en la caja, saliendo del establecimiento y volviendo a entrar para comprar la siguiente. Usar transacciones es poner todo en el carrito y pagar una sola vez.",
    interactive_challenge: ">> DESAFÍO: Envuelve una carga múltiple de inserts en una sola transacción explícita. Compara la velocidad de respuesta y reclama 200 XP."
  },
  "2-1": {
    consejos: [
      "FTS5 es ideal para motores de búsqueda internos. Genera índices invertidos que realizan búsquedas de palabras clave en milisegundos.",
      "Recuerda que la tabla virtual FTS5 debe mantenerse sincronizada con tu tabla real mediante triggers si modificas datos frecuentemente."
    ],
    ideas: [
      "Crea un trigger que inserte automáticamente en la tabla virtual de búsqueda FTS5 cada vez que añadas una nueva fila en tu tabla de registros común.",
      "Prueba el operador NEAR de FTS5 para buscar palabras que estén cerca de otras."
    ],
    casosDeUso: [
      "Buscador de contactos o mensajes de chat en una app local de mensajería (ej: WhatsApp/Telegram desktop).",
      "Búsqueda rápida en manuales de ayuda offline de herramientas de software."
    ],
    casosReales: [
      "Una aplicación de notas personales implementó búsqueda global instantánea sobre 100,000 notas usando FTS5, reduciendo la la latencia de búsqueda a menos de 5ms en dispositivos de gama baja."
    ],
    noticias: [
      "El módulo FTS5 continúa recibiendo optimizaciones de memoria para permitir indexación de texto sumamente pesado sin saturar la RAM."
    ],
    lore_context: "Debemos hackear el motor de búsqueda del archivo imperial de la Estrella de la Muerte. Hacer un LIKE '%planos%' tardará demasiado en el procesador embebido de la patrulla.",
    technical_deep_dive: "El módulo FTS5 (Full-Text Search 5) crea tablas virtuales que pre-indexan cada palabra (tokenización) usando estructuras de índice invertido similares a Elasticsearch. Esto permite búsquedas complejas con operadores booleanos y proximidad (NEAR) en microsegundos, evitando escaneos de texto completo (LIKE) en disco.",
    visual_analogy: "Buscar con LIKE es leer cada página de una enciclopedia de 1000 páginas de inicio a fin buscando una frase. Buscar con FTS5 es ir directamente al índice alfabético del final del libro y saltar a la página exacta.",
    interactive_challenge: ">> DESAFÍO: Crea una tabla virtual con FTS5, carga texto confidencial y haz una búsqueda usando el operador de proximidad NEAR. Desbloquea 250 XP."
  },
  "2-2": {
    consejos: [
      "Las funciones de JSON en SQLite son muy rápidas. Puedes almacenar un string JSON en una columna TEXT y consultarlo con operadores flecha (`->` y `->>`).",
      "Para optimizar búsquedas JSON, puedes crear índices sobre columnas generadas basadas en propiedades específicas del JSON."
    ],
    ideas: [
      "Usa `json_each` para iterar sobre un array almacenado dentro del documento JSON.",
      "Escribe un query para verificar la validez de un JSON usando la función `json_valid()`."
    ],
    casosDeUso: [
      "Guardar configuraciones de usuario personalizables que tienen esquemas dinámicos.",
      "Almacenar respuestas de servicios web locales para visualización posterior en apps offline."
    ],
    casosReales: [
      "Un desarrollador de videojuegos guardaba el inventario del jugador como columnas individuales. Cada vez que añadía un objeto, debía alterar la tabla. Migró a un campo JSON, lo que le permitió actualizar el inventario dinámicamente sin alterar la estructura física de la base de datos."
    ],
    noticias: [
      "A partir de la versión 3.38, SQLite incorporó soporte de operadores JSON estándar (`->` y `->>`) de forma nativa e integrada sin requerir activar módulos externos."
    ],
    lore_context: "El enemigo transmite datos dinámicos de sus patrullas en formato JSON serializado. No tenemos tiempo para parsearlo en el código del microcontrolador; el procesador SQLite debe extraer los datos al vuelo.",
    technical_deep_dive: "SQLite no tiene un tipo de datos JSON binario nativo como JSONB de Postgres; almacena JSON como texto (TEXT). Sin embargo, la extensión JSON1 (integrada de forma nativa desde v3.38) proporciona funciones ultra optimizadas y operadores flecha (-> y ->>) que parsean el string directamente en memoria C.",
    visual_analogy: "Guardar JSON en SQLite es como guardar una carta escrita a mano en un sobre cerrado. Las funciones JSON son como tener un asistente ultrarrápido que abre el sobre, lee la línea que le pides y lo vuelve a cerrar de inmediato.",
    interactive_challenge: ">> DESAFÍO: Utiliza json_each para iterar y extraer elementos específicos de un array JSON embebido. Obtén 300 XP."
  },
  "2-3": {
    consejos: [
      "Por razones de rendimiento histórico, SQLite no activa las restricciones de clave foránea (Foreign Keys) por defecto. Debes ejecutar `PRAGMA foreign_keys = ON;` al abrir cada conexión.",
      "Las vistas en SQLite son de solo lectura. No puedes ejecutar sentencias INSERT o UPDATE directamente en una vista ordinaria."
    ],
    ideas: [
      "Intenta realizar una inserción con una llave foránea inválida antes y después de ejecutar `PRAGMA foreign_keys = ON;` para notar la diferencia.",
      "Crea una vista que una datos usando alias claros y úsala en un SELECT simple."
    ],
    casosDeUso: [
      "Asegurar integridad estructural en proyectos escolares o de desarrollo rápido locales.",
      "Abstraer reportes acumulados complejos en vistas limpias para visualización en dashboards."
    ],
    casosReales: [
      "Una aplicación de gestión escolar local comenzó a generar inconsistencias: alumnos sin clases asignadas y registros huérfanos. Se descubrió que la base de datos SQLite no tenía activada la pragma de foreign keys en el hilo de escritura, permitiendo la corrupción silenciosa de datos relacionales."
    ],
    noticias: [
      "Hay discusiones en el foro oficial de SQLite sobre habilitar claves foráneas por defecto en futuras revisiones mayores, aunque el impacto de compatibilidad hacia atrás es un factor limitante."
    ],
    lore_context: "Nuestros espías reportaron que el sistema de control del Imperio está registrando alumnos sin clases válidas. Las llaves foráneas están desactivadas por defecto. Debemos forzar la integridad relacional.",
    technical_deep_dive: "Por razones de retrocompatibilidad y rendimiento en dispositivos antiguos de baja potencia, SQLite tiene las restricciones de llaves foráneas desactivadas por defecto. Es obligatorio ejecutar PRAGMA foreign_keys = ON; al inicio de cada conexión de base de datos para habilitar la integridad referencial.",
    visual_analogy: "Las llaves foráneas en SQLite desactivadas son como tener un guardia de seguridad en el banco que tiene prohibido pedir identificaciones. Habilitar la PRAGMA es darle al guardia la orden explícita de verificar cada pase de entrada.",
    interactive_challenge: ">> DESAFÍO: Habilita la integridad relacional usando PRAGMA e intenta insertar una nave vinculada a un piloto inexistente para validar el bloqueo. Obtén 350 XP."
  },
  "3-1": {
    consejos: [
      "SQLite soporta triggers limitados pero muy potentes. La función `RAISE` dentro de un trigger es la herramienta ideal para abortar transacciones con un mensaje de error personalizado.",
      "Evita triggers complejos que hagan llamados en cadena en SQLite; el motor es monohilo en escrituras y puede bloquear la base de datos ante sobrecarga."
    ],
    ideas: [
      "Crea un trigger que auto-incremente una columna de contador de visitas cada vez que una base sea consultada o modificada.",
      "Usa un trigger INSTEAD OF sobre una vista para simular inserciones en tablas unidas de forma inteligente."
    ],
    casosDeUso: [
      "Validar reglas complejas de negocio que no pueden validarse con constraints tradicionales (ej: límites de registros totales).",
      "Mantener campos actualizados de forma autónoma, como una columna `fecha_modificacion`."
    ],
    casosReales: [
      "Un software de inventario local implementó auditoría automática de salidas de caja usando triggers en SQLite. Incluso cuando los usuarios accedían a la base de datos desde clientes genéricos externos, la auditoría seguía funcionando impecablemente."
    ],
    noticias: [
      "El compilador de triggers de SQLite se ha reescrito internamente para generar código de bytecode más corto, lo que acelera su velocidad de ejecución en un 15%."
    ],
    lore_context: "El reactor está a punto de sobrecalentarse. Si alguien intenta cambiar la temperatura de seguridad por encima de los límites recomendados, el trigger debe abortar la operación físicamente en la memoria flash.",
    technical_deep_dive: "Los triggers en SQLite son muy útiles para la automatización a nivel de cliente. Al no poseer un lenguaje procedimental (como PL/SQL), SQLite provee la función especial RAISE(ABORT, 'mensaje') dentro del trigger. Esto permite abortar la transacción DML en curso y lanzar un error personalizado.",
    visual_analogy: "Un trigger con RAISE es como un fusible eléctrico en un panel de control. Si la corriente supera un nivel peligroso, el fusible se quema y corta la electricidad al instante para salvar el equipo.",
    interactive_challenge: ">> DESAFÍO: Crea un trigger que use RAISE(ABORT, ...) para bloquear cambios sospechosos de créditos superiores al límite y reclama 400 XP."
  },
  "3-2": {
    consejos: [
      "SQLite no cuenta con un lenguaje procedimental integrado completo como PL/pgSQL de Postgres. Las consultas complejas se resuelven combinando CTEs avanzados o escribiendo funciones personalizadas en el lenguaje del host (ej: JavaScript/Node).",
      "WITH RECURSIVE es excelente para modelar datos de grafos o árboles jerárquicos de forma compacta."
    ],
    ideas: [
      "Utiliza un CTE recursivo para generar una tabla con los primeros 15 números de la serie Fibonacci.",
      "Escribe un query recursivo que dibuje un árbol simple en caracteres ASCII usando concatenaciones."
    ],
    casosDeUso: [
      "Generación de reportes de organigramas jerárquicos de empleados dentro de la base de datos portátil.",
      "Búsqueda recursiva de dependencias de archivos en sistemas de compilación locales."
    ],
    casosReales: [
      "Un gestor de tareas local utilizaba llamadas repetitivas al backend para reconstruir árboles de subtareas. Al migrar la lógica a un CTE recursivo en SQLite, la interfaz pasó de tardar 300ms en renderizar a menos de 5ms."
    ],
    noticias: [
      "Las CTEs recursivas de SQLite son de las implementaciones más fieles al estándar SQL ANSI de toda la industria."
    ],
    lore_context: "El Imperio organiza sus comandos en árboles jerárquicos complejos. Debemos descifrar la cadena de mando completa partiendo desde un soldado de infantería hasta llegar al Emperador.",
    technical_deep_dive: "SQLite tiene soporte completo para Standard SQL, incluyendo CTEs recursivos (WITH RECURSIVE). Esto permite resolver estructuras de grafos y árboles jerárquicos en una sola consulta recursiva interna, evitando el overhead de código recursivo en el host.",
    visual_analogy: "Recorrer un árbol genealógico sin recursividad es como buscar a los ancestros llamando a cada familiar uno por uno y anotándolo en una libreta. Con recursividad, le dices a la base de datos: 'Tráeme a toda la línea de sangre en un solo viaje de regreso'.",
    interactive_challenge: ">> DESAFÍO: Escribe una consulta recursiva que genere la secuencia de Fibonacci en el sandbox de SQLite y reclama 450 XP."
  },
  "3-3": {
    consejos: [
      "Usa `PRAGMA journal_mode = WAL;` (Write-Ahead Logging) en tus proyectos SQLite. Habilita lecturas y escrituras simultáneas sin bloqueos mutuos, aumentando radicalmente el rendimiento de concurrencia.",
      "Configura `PRAGMA synchronous = NORMAL;` junto con WAL para obtener una combinación ideal de velocidad y seguridad ante fallos."
    ],
    ideas: [
      "Ejecuta `PRAGMA integrity_check;` para verificar si el archivo de la base de datos local sufre de algún tipo de corrupción de datos.",
      "Modifica la pragma de tamaño de caché (`cache_size`) y mide el impacto en la ejecución de consultas de lectura pesadas."
    ],
    casosDeUso: [
      "Optimizar el rendimiento de apps multi-hilo donde múltiples procesos leen la base de datos local mientras uno solo escribe.",
      "Verificación rápida de la salud estructural del archivo sqlite en procesos de despliegue."
    ],
    casosReales: [
      "Un servidor web ligero utilizaba SQLite para almacenar sesiones de usuarios. Ante 50 peticiones simultáneas, el sitio lanzaba errores 'Database is locked'. Al activar `PRAGMA journal_mode = WAL;`, el sitio soportó más de 500 peticiones por segundo sin un solo error de bloqueo."
    ],
    noticias: [
      "SQLite es el software de base de datos más distribuido del planeta; corre en cada smartphone, sistema operativo, avión comercial, automóvil moderno y navegador."
    ],
    lore_context: "Varios procesos espía intentan leer y escribir en la base de datos simultáneamente. El sistema lanza errores de base de datos bloqueada constantemente. Debemos activar el protocolo de alto rendimiento WAL.",
    technical_deep_dive: "Por defecto, SQLite usa rollback journal, bloqueando todo el archivo para escrituras. Activar PRAGMA journal_mode = WAL; (Write-Ahead Logging) crea un archivo .wal temporal donde se escriben los cambios, permitiendo que múltiples lectores leen simultáneamente sin bloquearse.",
    visual_analogy: "El modo journal normal es como tener un solo libro en la biblioteca que debes cerrar y guardar bajo llave cada vez que alguien escribe una nota. WAL es como hacer anotaciones en una libreta borrador separada mientras todos los demás siguen leyendo el libro principal.",
    interactive_challenge: ">> DESAFÍO: Activa el modo WAL y ejecuta un integrity_check en el sandbox para certificar que el archivo no está corrupto. Reclama el nivel Máster de SQLite con 500 XP."
  }
};

// Generador de fallbacks inteligentes para el resto de motores para garantizar escalabilidad
const createFallbackChapters = (engineId: string): Record<string, EnrichedChapter> => {
  const titles: Record<string, string> = {
    "1-1": "Estructuras Fundamentales",
    "1-2": "Restricciones y Seguridad",
    "1-3": "Manipulación de Datos",
    "2-1": "Relaciones y Joins de Alta Velocidad",
    "2-2": "Optimización y Datos Complejos",
    "2-3": "Abstracción con Vistas",
    "3-1": "Automatización y Triggers",
    "3-2": "Lógica y Procedimientos Almacenados",
    "3-3": "Características Especiales del Motor"
  };

  const getEngineSpecs = (id: string) => {
    switch (id) {
      case "mysql":
        return {
          name: "MySQL",
          incidente: "Un bloqueo de filas (Row Locks) mal configurado en InnoDB colapsó el sistema de pagos de una pasarela durante el Black Friday por no usar índices correctos.",
          noticia: "MySQL 8.4 LTS introdujo mejoras considerables en el optimizador y en la gestión de credenciales seguras.",
          curiosidad: "MySQL originalmente no soportaba transacciones ni claves foráneas hasta que adoptó el motor de almacenamiento InnoDB."
        };
      case "mariadb":
        return {
          name: "MariaDB",
          incidente: "Un desarrollador borró accidentalmente el historial de una tabla con System Versioning. Aunque los datos seguían ahí en el tiempo, costó 3 horas reconstruir las referencias cruzadas.",
          noticia: "MariaDB continúa distanciándose de MySQL ofreciendo características de versionado temporal nativas incomparables.",
          curiosidad: "MariaDB fue creada por el creador original de MySQL, Michael 'Monty' Widenius, quien la nombró por su segunda hija, Maria."
        };
      case "oracle":
        return {
          name: "Oracle Database",
          incidente: "Una mala configuración de tablespaces (espacio de almacenamiento físico) dejó a un banco nacional sin sistema de cajeros automáticos durante toda una noche.",
          noticia: "Oracle 23c Free Edition ('App Simple') ha simplificado drásticamente el desarrollo local agregando soporte JSON nativo de nivel JSON Relational Duality.",
          curiosidad: "En Oracle, las transacciones nunca se guardan solas (no hay autocommit en clientes tradicionales como SQL*Plus), requiriendo un COMMIT explícito."
        };
      case "sqlserver":
        return {
          name: "SQL Server (T-SQL)",
          incidente: "Un bloqueo exclusivo a nivel de base de datos debido a un reporte sin la directiva WITH (NOLOCK) detuvo la facturación de una cadena de supermercados por 30 minutos.",
          noticia: "Microsoft SQL Server 2022 integra de manera fluida análisis de datos con Azure Synapse Link y soporte para Ledger tables (tablas de blockchain locales).",
          curiosidad: "SQL Server fue desarrollado originalmente en conjunto entre Microsoft, Sybase y Ashton-Tate a finales de los años 80."
        };
      default:
        return {
          name: id,
          incidente: "Error de configuración de permisos detuvo la conexión del servidor local.",
          noticia: "Nuevas actualizaciones del motor optimizan el planificador de queries.",
          curiosidad: "Las bases de datos relacionales surgieron en 1970 gracias al paper científico de Edgar F. Codd."
        };
    }
  };

  const specs = getEngineSpecs(engineId);

  const dict: Record<string, EnrichedChapter> = {};

  for (const key of Object.keys(titles)) {
    dict[key] = {
      consejos: [
        `Agente, en ${specs.name}, siempre monitorea el uso de índices. No podemos permitirnos un escaneo secuencial en medio de una auditoría corporativa.`,
        "Mantén la consistencia. Los sistemas gubernamentales detectan anomalías a kilómetros; usa nombres de tablas consistentes (minúsculas/mayúsculas) según el SO."
      ],
      ideas: [
        "Infiltra unas filas extra en tu terminal SQL y ejecuta una agrupación (GROUP BY). Veamos cómo se comporta el motor bajo presión.",
        "Genera un fallo de tipado intencional. Conocer cómo falla el enemigo (el motor) te enseña cómo dominarlo."
      ],
      casosDeUso: [
        `Flujos CRUD de alta disponibilidad para ledgers intocables utilizando las bóvedas de ${specs.name}.`,
        "Auditoría interna rápida y almacenamiento eficiente de registros históricos para cuando el gobierno nos pida explicaciones."
      ],
      casosReales: [
        specs.incidente
      ],
      noticias: [
        specs.noticia,
        `Archivo clasificado: ${specs.curiosidad}`
      ],
      lore_context: `[SEÑAL ENCRIPTADA RECIBIDA] Operativo, tu misión en la directiva ${key} (${titles[key]}) es dominar esta característica antes de que nuestro cliente pierda 5 millones en una transacción fantasma. La teoría es linda, pero aquí estamos para evitar colapsos. (muhahahahah).`,
      technical_deep_dive: `El motor ${specs.name} gestiona esto mediante su planificador interno. La diferencia entre la vida y la muerte de tu query radica en cómo este motor asigna memoria (buffer pool) vs lectura en disco sucio.`,
      visual_analogy: "Imagina que el motor es un búnker de máxima seguridad. Los índices son el mapa de los ductos de ventilación. Sin ellos, el guardia tiene que revisar cada cuarto (Full Table Scan) hasta encontrarte.",
      interactive_challenge: ">> MISIÓN ACTIVA: Conéctate a la terminal y ejecuta 5 inserts masivos dentro de una sola transacción. Si sobrevives sin bloquear la base de datos, ganas 50 Puntos de Maestría."
    };
  }

  return dict;
};

// Motores cacheados para evitar recreaciones
const fallbackCache: Record<string, Record<string, EnrichedChapter>> = {};

/**
 * Obtiene el contenido enriquecido de un motor y capítulo específico.
 * Retorna un fallback de calidad estructurado si el motor no tiene cargados datos específicos.
 *
 * @param engineId - Identificador del motor de base de datos (ej: postgres, sqlite)
 * @param moduleId - Identificador del módulo de aprendizaje (ej: 1-1, 3-2)
 * @returns El contenido educativo enriquecido estructurado
 */
export function getEnrichedContent(engineId: string, moduleId: string): EnrichedChapter {
  if (engineId === "postgres" && postgresChapters[moduleId]) {
    return postgresChapters[moduleId];
  }
  if (engineId === "sqlite" && sqliteChapters[moduleId]) {
    return sqliteChapters[moduleId];
  }

  // Generar o usar cache para otros motores
  if (!fallbackCache[engineId]) {
    fallbackCache[engineId] = createFallbackChapters(engineId);
  }

  return fallbackCache[engineId][moduleId] || {
    consejos: ["Aplica buenas prácticas de diseño de base de datos relacionales."],
    ideas: ["Realiza pruebas adicionales ejecutando código SQL en tu hoja de conexión."],
    casosDeUso: ["Sistemas corporativos con alta necesidad de transaccionalidad."],
    casosReales: ["Incidente menor por falta de índices en tablas de producción."],
    noticias: ["La comunidad activa de desarrollo sigue agregando soporte de estándares SQL."]
  };
}
